-- MySQL Script generated by MySQL Workbench
-- Mon Dec 10 23:29:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema omnis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema omnis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `omnis` DEFAULT CHARACTER SET utf8 ;
USE `omnis` ;

-- -----------------------------------------------------
-- Table `omnis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omnis`.`user` (
  `_id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `mail` VARCHAR(254) NOT NULL,
  `hashpass` VARCHAR(64) NOT NULL,
  `picture` VARCHAR(2048) NULL,
  `status` ENUM('A', 'I') NOT NULL DEFAULT 'A',
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omnis`.`flow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omnis`.`flow` (
  `_id` INT NOT NULL,
  `_id_user` INT NOT NULL,
  `uri` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_flow_user_idx` (`_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_flow_user` 
    FOREIGN KEY (`_id_user`) 
    REFERENCES `omnis`.`user` (`_id`) 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omnis`.`filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omnis`.`filter` (
  `_id` INT NOT NULL,
  `_id_flow` INT NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_filter_flow1_idx` (`_id_flow` ASC) VISIBLE,
  CONSTRAINT `fk_filter_flow1`
    FOREIGN KEY (`_id_flow`)
    REFERENCES `omnis`.`flow` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omnis`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omnis`.`topic` (
  `_id` INT NOT NULL,
  `_id_flow` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_topic_flow1_idx` (`_id_flow` ASC) VISIBLE,
  CONSTRAINT `fk_topic_flow1`
    FOREIGN KEY (`_id_flow`)
    REFERENCES `omnis`.`flow` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `omnis`.`user_activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omnis`.`user_activities` (
  `_id` INT NOT NULL,
  `_id_user` INT NOT NULL,
  `connection_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`_id`),
  INDEX `fk_user_activities_user1_idx` (`_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_activities_user1`
    FOREIGN KEY (`_id_user`)
    REFERENCES `omnis`.`user` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
